$inifile = @"
[OPTIONS]
ACTION="Install"
SUPPRESSPRIVACYSTATEMENTNOTICE="False"
IACCEPTROPENLICENSETERMS="False"
ENU="True"
QUIET="False"
QUIETSIMPLE="True"
;UIMODE="Normal"
UpdateEnabled="False"
USEMICROSOFTUPDATE="False"
FEATURES=SQLENGINE,RS
UpdateSource="MU"
HELP="False"
INDICATEPROGRESS="False"
X86="False"
INSTANCENAME="MSSQLSERVER"
INSTALLSHAREDDIR="C:\SQLServer"
INSTALLSHAREDWOWDIR="C:\SQLServer (x86)"
INSTANCEID="MSSQLSERVER"
RSINSTALLMODE="DefaultNativeMode"
SQLTELSVCACCT="NT Service\SQLTELEMETRY"
SQLTELSVCSTARTUPTYPE="Automatic"
INSTANCEDIR="C:\SQLServer"
AGTSVCACCOUNT="NT AUTHORITY\SYSTEM"
AGTSVCSTARTUPTYPE="Manual"
COMMFABRICPORT="0"
COMMFABRICNETWORKLEVEL="0"
COMMFABRICENCRYPTION="0"
MATRIXCMBRICKCOMMPORT="0"
SQLSVCSTARTUPTYPE="Automatic"
FILESTREAMLEVEL="0"
ENABLERANU="False"
SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS"
SQLSVCACCOUNT="NT AUTHORITY\SYSTEM"
SQLSVCINSTANTFILEINIT="False"
SQLSYSADMINACCOUNTS="CLASSROOM\SCCM Admins"
SQLTEMPDBFILECOUNT="2"
SQLTEMPDBFILESIZE="1024"
SQLTEMPDBFILEGROWTH="64"
SQLTEMPDBLOGFILESIZE="1024"
SQLTEMPDBLOGFILEGROWTH="64"
ADDCURRENTUSERASSQLADMIN="False"
TCPENABLED="1"
NPENABLED="0"
BROWSERSVCSTARTUPTYPE="Disabled"
RSSVCACCOUNT="NT AUTHORITY\SYSTEM"
RSSVCSTARTUPTYPE="Automatic"
"@

$inifile  -replace "`n", "`r`n" | Out-File -FilePath "\\srv0001\TempFiles\installsql2016.ini"

Start-Process -Filepath ("\\srv0001\TrainingFiles\Source\SQL2016\setup.exe") -ArgumentList ('/ConfigurationFile="\\srv0001\TempFiles\\installsql2016.ini" /IAcceptSQLServerLicenseTerms') -wait
Start-sleep 30

$web = New-Object -ComObject msxml2.xmlhttp
$url = "http://localhost:80/reports"
try {   
	$web.open('GET', $url, $false)
	$web.send()
			
	Write-host "HTTP Return $($web.status)"
} catch {
	Write-host "ERROR: $($_)"
}
